steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/snowf-101tot/demo-flask-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/snowf-101tot/demo-flask-app']

- name: 'gcr.io/snowf-101tot/demo-flask-app'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'demo-flask-app'
   - '--image'
   - 'gcr.io/snowf-101tot/demo-flask-app'
   - '--region'
   - 'us-central1'
   - '--allow-unauthenticated'
images:
- 'gcr.io/snowf-101tot/demo-flask-app'

options:
  logging: CLOUD_LOGGING_ONLY